import ProvidersWrappers from "@/components/ProvidersWrappers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AdminSidebar from "@/components/AdminSidebar"; // {{ edit_1 }}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ 
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className} style={{ display: 'flex' }}> {/* {{ edit_1 }} */}
                <AdminSidebar /> {/* {{ edit_3 }} */}
                <div style={{ flex: 1 }}>{children}</div> {/* {{ edit_2 }} */}
            </body>
        </html>
    );
}
